[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "PORT=${PORT:-3000} node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

